# Generated by Django 4.1.5 on 2023-02-03 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_id', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('post_number', models.IntegerField(null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('co_adress', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('payment_way', models.CharField(max_length=500)),
                ('user_id', models.IntegerField(null=True)),
                ('discount_code', models.CharField(max_length=8)),
                ('state', models.BooleanField(default=False)),
                ('discount_id', models.IntegerField(null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(null=True)),
                ('prod_id', models.IntegerField(null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=300)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='creator_admin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='deleted_by_admin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='admin_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prod_category',
            name='car_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prod_category',
            name='prod_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creator_admin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by_admin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discout_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='review_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='prod_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
