# Generated by Django 4.1.5 on 2023-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0002_adress_order_prod_cart_shopping_cart_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Prod_cart',
        ),
        migrations.DeleteModel(
            name='Prod_category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Shopping_cart',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='administrators',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
