# Generated by Django 4.1.5 on 2023-02-04 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0003_delete_adress_delete_categories_delete_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('deleted_by_admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.administrators')),
            ],
        ),
    ]
