# Generated by Django 4.1.5 on 2023-02-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='creator_admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_admin_id', to='gameshop.administrators'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='deleted_by_admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_admin_id', to='gameshop.administrators'),
        ),
    ]
