# Generated by Django 4.1.5 on 2023-02-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0007_product_prod_category_delete_prod_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cart',
            field=models.ManyToManyField(to='gameshop.shopping_cart'),
        ),
        migrations.DeleteModel(
            name='Prod_cart',
        ),
    ]
