# Generated by Django 4.1.5 on 2023-02-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0008_delete_games_product_prod_cart_delete_prod_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discout_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.review'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.product')),
            ],
        ),
    ]
