# Generated by Django 4.1.5 on 2023-02-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0011_alter_categories_creator_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_id',
        ),
        migrations.AlterField(
            model_name='adress',
            name='order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.user'),
        ),
    ]
