# Generated by Django 4.1.5 on 2023-02-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0012_remove_order_discount_id_alter_adress_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.discount'),
        ),
    ]
