# Generated by Django 4.1.7 on 2023-03-14 08:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameshop', '0016_alter_shopping_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Favorite_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
