# Generated by Django 4.1.7 on 2023-03-15 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0017_alter_discount_code_alter_discount_discount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.order')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.product')),
            ],
        ),
    ]
