# Generated by Django 4.1.7 on 2023-03-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0018_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discout_id',
            new_name='discount_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_id',
        ),
    ]
