# Generated by Django 4.1.5 on 2023-03-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0019_rename_discout_id_product_discount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_cart',
        ),
        migrations.AddField(
            model_name='product',
            name='shopping_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gameshop.shopping_cart'),
        ),
    ]
