# Generated by Django 4.1.5 on 2023-03-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0020_remove_product_prod_cart_product_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cart',
            field=models.ManyToManyField(null=True, to='gameshop.shopping_cart'),
        ),
    ]
