# Generated by Django 4.1.5 on 2023-02-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0010_rename_productimages_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='creator_admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_admin_id', to='gameshop.administrators'),
        ),
    ]
